# Generated by Django 2.1.7 on 2019-10-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('dataset', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('controlled_terms', models.CharField(max_length=100)),
                ('adam_class', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('variable_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('library', models.CharField(max_length=100)),
                ('subject_data', models.CharField(max_length=100)),
                ('column_variable', models.CharField(max_length=100)),
                ('filter', models.CharField(max_length=1000)),
                ('stat_label', models.CharField(max_length=1000)),
                ('report_type', models.CharField(max_length=100)),
                ('template', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Reports',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReportHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportheaders', to='studyui.Report')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReportHeaderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('column_condition', models.CharField(max_length=100)),
                ('column_order', models.CharField(max_length=100)),
                ('column_label', models.CharField(max_length=100)),
                ('reportheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportheaderdetails', to='studyui.ReportHeader')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReportSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=100)),
                ('library', models.CharField(max_length=100)),
                ('dataset', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=1000)),
                ('filter', models.CharField(max_length=1000)),
                ('analysis', models.CharField(max_length=100)),
                ('additional_variables', models.CharField(max_length=1000, null=True)),
                ('special_variables', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportsegments', to='studyui.Report')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReportSegmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('reportsegment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportsegmentdetails', to='studyui.ReportSegment')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReportSubset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('population_subset', models.CharField(max_length=100)),
                ('analysis_subset', models.CharField(max_length=100)),
                ('population_title', models.CharField(max_length=1000)),
                ('analysis_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportsubsets', to='studyui.Report')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='studyui.Report')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=200, null=True)),
                ('indication', models.CharField(max_length=1000, null=True)),
                ('crossover', models.BooleanField(default=False)),
                ('output_type', models.CharField(max_length=200, null=True)),
                ('protocol', models.CharField(max_length=200, null=True)),
                ('sap', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=1000)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='studyui.Molecule')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='studyui.Trial'),
        ),
        migrations.AddField(
            model_name='reportheader',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskheaders', to='studyui.Task'),
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='studyui.Task'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatas', to='studyui.Task'),
        ),
        migrations.AddField(
            model_name='footnote',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='studyui.Report'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('studyui.report',),
        ),
    ]
